# Generic programming

We have seen **duck typing** as a convient abstraction tool for data types:

* As a **user**, we don't have to care about how a specific type, say an `Array`, is implemented. By being an array (i.e. a subtype of `AbstractArray`) it behaves like we expect and we can just use it.
* As a **developer**, as long as we make our objects behave like, say, and `AbstractArray`, we can implement it in whatever way we deem appropriate and it will work with all kinds of algorithms.

Building upon this principle, we also want to formulate our **algorithms** in an abstract way such that it works will all kinds of data types irrespective of their precise implementation (or even meaning). This is generally known as **generic programming**.

From [Wikipedia](https://en.wikipedia.org/wiki/Generic_programming):

> **Generic programming** is a style of computer programming in which algorithms are written in terms of types *to-be-specified-later* that are then *instantiated* when needed for specific types provided as parameters.

## Example 1: Summation

In [2]:
function sum_naive(x)
    s = 0.0
    for xi in x
        s += xi
    end
    return s
end

sum_naive (generic function with 1 method)

In [3]:
function sum_generic(x)
    s = zero(eltype(x))
    for xi in x
        s += xi
    end
    return s
end

sum_generic (generic function with 1 method)

In [4]:
using BenchmarkTools

In [5]:
x = rand(100_000);
@btime sum_naive($x);
@btime sum_generic($x);

  154.262 μs (0 allocations: 0 bytes)
  154.259 μs (0 allocations: 0 bytes)


In [6]:
x = rand(Int, 100_000);
@btime sum_naive($x);
@btime sum_generic($x);

  154.269 μs (0 allocations: 0 bytes)
  19.040 μs (0 allocations: 0 bytes)


### Example 2: Vandermonde matrix
(modified from [Steven's Julia intro](https://web.mit.edu/18.06/www/Fall17/1806/julia/Julia-intro.pdf))

\begin{align}V=\begin{bmatrix}1&\alpha _{1}&\alpha _{1}^{2}&\dots &\alpha _{1}^{n-1}\\1&\alpha _{2}&\alpha _{2}^{2}&\dots &\alpha _{2}^{n-1}\\1&\alpha _{3}&\alpha _{3}^{2}&\dots &\alpha _{3}^{n-1}\\\vdots &\vdots &\vdots &\ddots &\vdots \\1&\alpha _{m}&\alpha _{m}^{2}&\dots &\alpha _{m}^{n-1}\end{bmatrix}\end{align}

In [7]:
using PythonCall

    CondaPkg Found dependencies: /Users/crstnbr/repos/JuliaWorkshops/JuliaHLRS22/CondaPkg.toml
    CondaPkg Found dependencies: /Users/crstnbr/.julia/packages/PythonCall/DqZCE/CondaPkg.toml
    CondaPkg Dependencies already up to date


In [8]:
np = pyimport("numpy")

Python module: <module 'numpy' from '/Users/crstnbr/repos/JuliaWorkshops/JuliaHLRS22/.CondaPkg/env/lib/python3.10/site-packages/numpy/__init__.py'>

In [9]:
np.vander(1:5, increasing=true)

Python ndarray:
array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]])

The source code for this function is [here](https://github.com/numpy/numpy/blob/v1.16.1/numpy/lib/twodim_base.py#L475-L563). It calls `np.multiply.accumulate` which is implemented in C [here](https://github.com/numpy/numpy/blob/deea4983aedfa96905bbaee64e3d1de84144303f/numpy/core/src/umath/ufunc_object.c#L3678). However, this code doesn't actually perform the computation, it basically only checks types and stuff. The actual kernel that gets called is [here](https://github.com/numpy/numpy/blob/deea4983aedfa96905bbaee64e3d1de84144303f/numpy/core/src/umath/loops.c.src#L1742). This isn't even C code but a template for C code which is used to generate type specific kernels.

Overall, this setup only supports a limited set of types, like `Float64`, `Float32`, and so forth.

Here is our simple generic Julia implementation


In [10]:
function vander(x::AbstractVector{T}) where T
    m = length(x)
    V = Matrix{T}(undef, m, m)
    for j = 1:m
        V[j,1] = one(x[j])
    end
    for i= 2:m
        for j = 1:m
            V[j,i] = x[j] * V[j,i-1]
            end
        end
    return V
end

vander (generic function with 1 method)

In [11]:
vander(1:5)

5×5 Matrix{Int64}:
 1  1   1    1    1
 1  2   4    8   16
 1  3   9   27   81
 1  4  16   64  256
 1  5  25  125  625

#### A quick speed comparison


 <img src="../imgs/vandermonde.svg" alt="drawing" width="600"/>

Note that the clean and concise Julia implementation is **beating numpy's C implementation for small matrices** and is **on-par for large matrix sizes**.

At the same time, the Julia code is *generic* and works for arbitrary types!


In [12]:
vander(Int32[4, 8, 16, 32])

4×4 Matrix{Int32}:
 1   4    16     64
 1   8    64    512
 1  16   256   4096
 1  32  1024  32768

It even works for non-numerical types. The only requirement is that the type has a *one* (identity element) and a multiplication operation defined.


In [13]:
vander(["This", "is", "a", "test"])

4×4 Matrix{String}:
 ""  "This"  "ThisThis"  "ThisThisThis"
 ""  "is"    "isis"      "isisis"
 ""  "a"     "aa"        "aaa"
 ""  "test"  "testtest"  "testtesttest"

### New "features" emerging from generic programming

#### Symbolic computations

In [14]:
using Symbolics

In [15]:
@variables a b c d e

5-element Vector{Num}:
 a
 b
 c
 d
  e

In [16]:
v = vander([a,b,c,d,e])

5×5 Matrix{Num}:
 1  a   a^2     a^3     a^4
 1  b   b^2     b^3     b^4
 1  c   c^2     c^3     c^4
 1  d   d^2     d^3     d^4
 1   e     e^2     e^3     e^4

In [17]:
substitute(v, Dict(b => 2, d => 4))

5×5 Matrix{Num}:
 1  a   a^2     a^3     a^4
 1  2     4       8      16
 1  c   c^2     c^3     c^4
 1  4    16      64     256
 1   e     e^2     e^3     e^4

#### Arbitrary precision computing

In [18]:
x = rand(BigFloat, 10)

10-element Vector{BigFloat}:
 0.9208116449623347166192452264587084495853347987048726978611982918061241309514983
 0.8357086325739564792581509469125326361798917564772260970268599754632755899641744
 0.8756711626225916831578231553423143936705346142172390348791173085494828605439501
 0.7025893602087213959396535703047723255446537396745216740039550000722734115881833
 0.8746840695404426929898970564434091974957650027220359070552388425813315013099841
 0.6443687541263098797442322207846420494189076990517809480126157545777813336223175
 0.6307025207647385666030711242948852388339165529287342446149364636899798509671811
 0.2078318991231677091980418013527284233813502296243400822347784954400187322951034
 0.9802775367551366030536764786734507098202448714362707968456007613719105154740548
 0.5718410063260819209378380424992385646613682806961082897445397320392076579957134

In [19]:
sum(x)

7.244486587003481647501629623066681988591967545533129772278840625591385584712169

#### Differential equation solving with uncertainty

**Code:**
```julia
using OrdinaryDiffEq, Measurements, Plots

#Half-life of Carbon-14 is 5730 years.
c = 5.730 ± 2

#Setup
u0 = 1.0 ± 0.1
tspan = (0.0, 1.0)

#Define the problem
radioactivedecay(u,p,t) = -c*u

#Pass to solver
prob = ODEProblem(radioactivedecay,u0,tspan)
sol = solve(prob, Tsit5(), reltol=1e-8, abstol=1e-8);

plot(sol.t, sol.u, ylabel="u(t)", xlabel="t", lw=2, legend=false)
```

**Output:**
<img src="../imgs/ode_uncertainty.svg">

**Historical note**: In some sense, **Julia implemented that feature by itself**. The authors of Measurements.jl and DifferentialEquations.jl never had any collabration on this.

# Core messages of this Notebook

* Julia **can be fast.**
* **A function is compiled when called for the first time** with a given set of argument types.
* The are **multiple compilation steps** all of which can be inspected through macros like `@code_warntype`.
* **Code specialization** based on the types of all of the input arguments is important for speed.
* Calculations can be moved to compile-time to make run-time faster.
* In virtually all cases, **explicit type annotations are irrelevant for performance**.
* Type annotations in function signatures define a **type filter/user interface**.
